---
application:
  name: "client"
  project: "gico"
  organization: "QoveryCommunity"
routers:
- name: "main-client"
  custom_domains:
  - branch: main
    domain: web.gico-db.it
  routes:
  - application_name: "client"
    paths:
    - "/*"
